name: roqqu
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+13
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  adaptive_theme: ^3.7.0
  candlesticks: ^2.1.0
  dartx: ^1.2.0
  dio: ^5.7.0
  envied: ^0.5.4+1
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_i18n: ^0.36.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.2.8
  go_router_paths: ^0.2.2
  interactive_chart: ^0.3.5
  intl: ^0.19.0
  json_serializable: ^6.8.0
  loader_overlay: ^4.0.3
  overlay_support: ^2.1.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  spider: ^4.2.2
  toastification: ^2.3.0
  web_socket_channel: ^3.0.2



dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Black.ttf
      - asset: assets/fonts/Poppins-BlackItalic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
